### ISSUE TITLE
PhantomJS is depreciated/suspended

### ISSUE THREAD

**Issue by stevenhuyn** [matomatical/UoM-WAM-Spam#1]
Running the script in its current form does not work due to the driver and Python throws an error saying PhantomJS is depreciated.

http://phantomjs.org/ says it is suspended in development.

**Comment by stevenhuyn** [comment]
I personally just used ChromeDriver in my fork.

**Comment by matomatical** [comment]
Thanks for the heads up. I just came back to study this semester and finished my last exam, so I'll update this now.
