### ISSUE TITLE
Alternatives to SMTP... too?

### ISSUE THREAD

**Issue by blueset** [matomatical/UoM-WAM-Spam#4]
As previously discussed in Facebook comments [[1], [2]], SMTP setup with Gmail could be complicated and less secure. 

Other solutions like [Pushbullet], [Telegram Bot], or [IFTTT webhook] could be considered as an alternative to this. All of them only require a single HTTPS request to deliver a message, and is relatively user friendly to set up. Personally I'm using Telegram Bot for different kinds of push notifications.

[1]: https://www.facebook.com/groups/cissa.unimelb/permalink/10157385937024282/?comment_id=10157386885279282&comment_tracking=%7B%22tn%22%3A%22R%22%7D
[2]: https://www.facebook.com/groups/cissa.unimelb/permalink/10157385937024282/?comment_id=10157386925924282&comment_tracking=%7B%22tn%22%3A%22R%22%7D
[Pushbullet]: https://docs.pushbullet.com/
[Telegram Bot]: https://core.telegram.org/bots/api
[IFTTT webhook]: https://ifttt.com/maker_webhooks

**Comment by matomatical** [comment]
You're right. I'll think about this some more.

P.S. As far as you are aware, is there anything in particular that is problematic about the SMTP logic causing the Gmail authentication problems?

**Comment by blueset** [comment]
Would definitely like to take a look into that if I don't have AI exam next week. 😂

**Comment by CaviarChen** [comment]
@matomatical 
I've added some alternative notification methods to it. Please have a look if you have time.

**Comment by matomatical** [comment]
Thanks, I'm looking forward to taking a close look when I get a chance!

**Comment by blueset** [comment]
Finished by #7, #9 and #10.
